use crate::user::model::{Role, User};

pub struct Space {
    pub id: String,
    pub identifier: String,
    pub category: String,
    pub custom_code: String,
    pub description: Option<String>,
    pub gmt_create: i64,
    pub gmt_modified: Option<i64>,
    pub has_superior_space: bool,
    pub icon: Option<String>,
    pub creator: String,
    pub modifier: Option<String>,
    pub name: String,
    pub parent: Option<String>,
    pub status: String,
    pub status_stage: String,
    pub type_identifier: String,
    pub tags: Option<String>,
    pub members: Vec<User>,
    pub roles: Vec<Role>,
}

pub struct SpaceWorkItem {
    pub id: String,
    pub identifier: String,
    pub assigned_to: String,
    pub category: String,
    pub creator: String,
    pub directory: String,
    pub document: String,
    pub finish_time: Option<i64>,
    pub gmt_create: i64,
    pub gmt_modified: Option<i64>,
    pub modifier: Option<String>,
    pub parent: Option<String>,
    pub serial_number: i32,
    pub space: Option<String>,
    pub space_type: String,
    pub status: String,
    pub status_stage: String,
    pub subject: String,
    pub update_status_at: i64,
    pub work_item_type: String,
}
