use chrono::{DateTime, Utc};

use crate::enums::{FieldType, ResourceType};
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::HashSet;
use std::ops::Deref;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Field {
    pub id: u64,
    pub identifier: String,
    pub gmt_create: DateTime<Utc>,
    pub gmt_modified: Option<DateTime<Utc>>,
    pub creator: String,
    pub modifier: Option<String>,
    pub name: String,
    pub name_en: String,
    pub display_name: String,
    pub description: Option<String>,
    pub field_type: FieldType,
    pub resource_type: ResourceType,
    pub format: Option<serde_json::Value>,
    pub default_value: Option<serde_json::Value>,
    pub options: Option<serde_json::Value>,
    pub is_required: bool,
    pub unit: Option<String>,
    pub verify_condition: Option<serde_json::Value>,
    pub position: i32,
    pub default_value_list: Option<serde_json::Value>,
    pub is_system_required: bool,
    pub hint: Option<String>,
    pub is_show_when_create: bool,
    pub is_hidden: bool,
    pub cascading_option: Option<serde_json::Value>,
    pub has_read_only_rule: bool,
    pub is_deleted: bool,
    pub organization: String,
    pub space: String,
    pub extra: Option<serde_json::Value>,
}

pub struct CreateFieldParam {
    pub name: String,
    pub name_en: String,
    pub display_name: String,
    pub description: Option<String>,
    pub field_type: FieldType,
    pub resource_type: ResourceType,
    pub format: Option<serde_json::Value>,
    pub default_value: Option<serde_json::Value>,
    pub options: Option<serde_json::Value>,
    pub is_required: bool,
    pub unit: Option<String>,
    pub verify_condition: Option<serde_json::Value>,
    pub default_value_list: Option<serde_json::Value>,
    pub hint: Option<String>,
    pub is_show_when_create: bool,
    pub is_hidden: bool,
    pub organization: String,
    pub extra: Option<serde_json::Value>,
}

impl Field {
    pub fn clone_work_item_set_fields(fields: &[Field], field_names: Vec<&str>) -> Vec<Field> {
        let filed_set = field_names.into_iter().collect::<HashSet<_>>();
        fields
            .iter()
            .filter(|v| filed_set.contains(v.name.deref()))
            .cloned()
            .map(|mut v| {
                v.resource_type = ResourceType::WorkItemSet;
                v
            })
            .collect()
    }
    pub fn new_sys_filed(
        CreateFieldParam {
            name,
            name_en,
            display_name,
            description,
            field_type,
            resource_type,
            format,
            default_value,
            options,
            is_required,
            unit,
            verify_condition,
            default_value_list,
            hint,
            is_show_when_create,
            is_hidden,
            organization,
            extra,
        }: CreateFieldParam,
        creator: impl Into<String>,
    ) -> Field {
        let id = uuid::Uuid::new_v4().to_string();
        Field {
            id: 0,
            identifier: id,
            gmt_create: Utc::now(),
            gmt_modified: None,
            creator: creator.into(),
            modifier: None,
            name,
            name_en,
            display_name,
            description,
            field_type,
            resource_type: resource_type.clone(),
            format,
            default_value,
            options,
            is_required,
            unit,
            verify_condition,
            position: 0,
            default_value_list,
            is_system_required: false,
            hint,
            is_show_when_create,
            is_hidden,
            cascading_option: None,
            has_read_only_rule: false,
            is_deleted: false,
            organization,
            space: "global".to_string(),
            extra,
        }
    }

    pub fn init_project_fields(organization: String) -> Vec<Field> {
        vec![
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "project_start_time".to_string(),
                    name_en: "project_start_time".to_string(),
                    display_name: "项目开始时间".to_string(),
                    description: Some("计划开始时间".into()),
                    field_type: FieldType::DateTime,
                    resource_type: ResourceType::Project,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "project_end_time".to_string(),
                    name_en: "project_end_time".to_string(),
                    display_name: "项目结束时间".to_string(),
                    description: Some("计划结束时间".into()),
                    field_type: FieldType::DateTime,
                    resource_type: ResourceType::Project,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization,
                    extra: None,
                },
                "system",
            ),
        ]
    }

    pub fn init_work_item_fields(organization: String) -> Vec<Field> {
        vec![
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "tag".to_string(),
                    name_en: "tag".to_string(),
                    display_name: "标签".to_string(),
                    description: Some("标签".into()),
                    field_type: FieldType::MultiSelect,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "status".to_string(),
                    name_en: "status".to_string(),
                    display_name: "状态".to_string(),
                    description: Some("标签".into()),
                    field_type: FieldType::Select,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "planned_labor_hour".to_string(),
                    name_en: "planned_labor_hour".to_string(),
                    display_name: "预计工时".to_string(),
                    description: Some("预计工时".into()),
                    field_type: FieldType::Intput,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "owner".to_string(),
                    name_en: "owner".to_string(),
                    display_name: "负责人".to_string(),
                    description: Some("负责人".into()),
                    field_type: FieldType::SelectUser,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "actual_labor_hour".to_string(),
                    name_en: "actual_labor_hour".to_string(),
                    display_name: "实际工时".to_string(),
                    description: Some("实际工时".into()),
                    field_type: FieldType::Intput,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "sprint".to_string(),
                    name_en: "sprint".to_string(),
                    display_name: "迭代".to_string(),
                    description: Some("迭代".into()),
                    field_type: FieldType::Select,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "belonging_project".to_string(),
                    name_en: "belonging_project".to_string(),
                    display_name: "归属项目".to_string(),
                    description: Some("归属项目".into()),
                    field_type: FieldType::Select,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "tracker".to_string(),
                    name_en: "tracker".to_string(),
                    display_name: "抄送人".to_string(),
                    description: Some("抄送人".into()),
                    field_type: FieldType::MultiSelectUser,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "participant".to_string(),
                    name_en: "participant".to_string(),
                    display_name: "参与者".to_string(),
                    description: Some("参与者".into()),
                    field_type: FieldType::MultiSelectUser,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "planned_start_time".to_string(),
                    name_en: "planned_start_time".to_string(),
                    display_name: "计划开始时间".to_string(),
                    description: Some("计划开始时间".into()),
                    field_type: FieldType::DateTime,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "planned_completion_time".to_string(),
                    name_en: "planned_completion_time".to_string(),
                    display_name: "计划完成时间".to_string(),
                    description: Some("计划完成时间".into()),
                    field_type: FieldType::DateTime,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "workitem_type".to_string(),
                    name_en: "workitem_type".to_string(),
                    display_name: "工作项类型".to_string(),
                    description: Some("工作项类型".into()),
                    field_type: FieldType::Select,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "priority".to_string(),
                    name_en: "priority".to_string(),
                    display_name: "优先级".to_string(),
                    description: Some("优先级".into()),
                    field_type: FieldType::Select,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "reason_for_not_fix".to_string(),
                    name_en: "reason_for_not_fix".to_string(),
                    display_name: "不修复理由".to_string(),
                    description: Some("不修复理由".into()),
                    field_type: FieldType::Select,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: Some(json! {
                        [
                            {
                                "label": "重复的缺陷",
                                "value": "重复的缺陷"
                            },
                            {
                                "label": "符合设计",
                                "value": "符合设计"
                            },
                            {
                                "label": "无法重现",
                                "value": "无法重现"
                            },
                            {
                                "label": "外部系统引入",
                                "value": "外部系统引入"
                            },
                            {
                                "label": "业务决策",
                                "value": "业务决策"
                            },
                        ]
                    }),
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "related_project_list".to_string(),
                    name_en: "related_project_list".to_string(),
                    display_name: "共享项目".to_string(),
                    description: Some("共享项目".into()),
                    field_type: FieldType::MultiSelect,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "story_points".to_string(),
                    name_en: "story_points".to_string(),
                    display_name: "Story Points".to_string(),
                    description: Some("Story Points".into()),
                    field_type: FieldType::Select,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "progress".to_string(),
                    name_en: "progress".to_string(),
                    display_name: "进度".to_string(),
                    description: Some("进度".into()),
                    field_type: FieldType::Intput,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "verifier".to_string(),
                    name_en: "verifier".to_string(),
                    display_name: "验证者".to_string(),
                    description: Some("验证者".into()),
                    field_type: FieldType::SelectUser,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "milestone_actual_finish_time".to_string(),
                    name_en: "milestone_actual_finish_time".to_string(),
                    display_name: "里程碑实际完成时间".to_string(),
                    description: Some("里程碑实际完成时间".into()),
                    field_type: FieldType::DateTime,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "serious_level".to_string(),
                    name_en: "serious_level".to_string(),
                    display_name: "严重程度".to_string(),
                    description: Some("严重程度".into()),
                    field_type: FieldType::Select,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "feedback_type".to_string(),
                    name_en: "feedback_type".to_string(),
                    display_name: "反馈类型".to_string(),
                    description: Some("反馈类型".into()),
                    field_type: FieldType::Select,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "exp_completion_time".to_string(),
                    name_en: "exp_completion_time".to_string(),
                    display_name: "期望完成时间".to_string(),
                    description: Some("期望完成时间".into()),
                    field_type: FieldType::DateTime,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "meaning".to_string(),
                    name_en: "meaning".to_string(),
                    display_name: "价值".to_string(),
                    description: Some("价值".into()),
                    field_type: FieldType::Star,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "working_effort".to_string(),
                    name_en: "working_effort".to_string(),
                    display_name: "工作量".to_string(),
                    description: Some("工作量".into()),
                    field_type: FieldType::Star,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "meaning_of_working_effort".to_string(),
                    name_en: "meaning_of_working_effort".to_string(),
                    display_name: "价值/工作量".to_string(),
                    description: Some("价值/工作量".into()),
                    field_type: FieldType::Intput,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "version".to_string(),
                    name_en: "version".to_string(),
                    display_name: "版本".to_string(),
                    description: Some("版本".into()),
                    field_type: FieldType::MultiSelect,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "summary_of_planned_labor_hour".to_string(),
                    name_en: "summary_of_planned_labor_hour".to_string(),
                    display_name: "预计工时汇总".to_string(),
                    description: Some("预计工时汇总".into()),
                    field_type: FieldType::Intput,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
            Self::new_sys_filed(
                CreateFieldParam {
                    name: "summary_of_actual_labor_hour".to_string(),
                    name_en: "summary_of_actual_labor_hour".to_string(),
                    display_name: "实际工时汇总".to_string(),
                    description: Some("实际工时汇总".into()),
                    field_type: FieldType::Intput,
                    resource_type: ResourceType::WorkItem,
                    format: None,
                    default_value: None,
                    options: None,
                    is_required: true,
                    unit: None,
                    verify_condition: None,
                    default_value_list: None,
                    hint: None,
                    is_show_when_create: true,
                    is_hidden: false,
                    organization: organization.clone(),
                    extra: None,
                },
                "system",
            ),
        ]
    }
}
